<?php
namespace Models\Currency;

require_once 'autoload.php';
require_once 'PHPUnit/Framework.php';


class currencyWebService
{
    public function getExchangeRate()
    {
        return 1;
    }
}

/**
 * Test class for CurrencyConverter.
 * Generated by PHPUnit on 2010-05-24 at 22:33:37.
 */
class CurrencyConverterTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var CurrencyConverter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new CurrencyConverter;
        $this->object->setCurrencyWebService(new currencyWebService);
    }

    public function testConvert()
    {
        $this->assertTrue(
           $this->object->convert('$1') == '$1.00'
        );
    }

    /**
     * Test nothing is broken
     **/
    public function testSetCurrencyWebService()
    {
        $this->assertTrue(
            $this->object->setCurrencyWebService(new currencyWebService) == NULL
        );
    }
}
?>
