<?php
require_once 'PHPUnit/Framework.php';


require_once '/Users/mikepearce/Sites/task/models/Display.php';

/**
 * Test class for Display.
 * Generated by PHPUnit on 2010-05-24 at 22:34:01.
 */
class DisplayTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Display
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Display;
    }

    public function testSetPadSize()
    {
        $this->assertEquals(NULL, $this->object->setPadSize(10));
    }


}
?>
