<?php
namespace Models\Core;

require_once 'autoload.php';
require_once 'PHPUnit/Framework.php';

use Models\Error\ErrorHandler;
use Models\Currency\CurrencyConverter;
use Models\Currency\CurrencyWebservice;


/**
 * Test class for Merchant.
 * Generated by PHPUnit on 2010-05-24 at 22:34:55.
 */
class MerchantTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Merchant
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Merchant;
        $this->object->setDataFile('/Users/mikepearce/Sites/task/data.csv');

        $tt = new TransactionTable;
        $eh = new ErrorHandler;
        $cc = new CurrencyConverter;
        $cw = new CurrencyWebservice();
        $tt->setErrorHandler($eh);
        $this->object->setCurrencyConverter($cc);
        $cc->setCurrencyWebService($cw);
        $this->object->setTransactionTable($tt);
        $this->object->setErrorHandler($eh);
    }

    /**
     */
    public function testSetDataFile()
    {
        $this->object->setDataFile('xxx');
        $this->assertEquals(
            'xxx',
            $this->object->getDatafile()
        );
    }

    /**
     */
    public function testGetTransactions()
    {
        $this->assertTrue(
            is_array($this->object->getTransactions(1))
        );
    }
}
?>
