<?php
namespace Models\Display;

//require_once 'autoload.php';
require_once 'PHPUnit/Extensions/OutputTestCase.php';


/**
 * Test class for Display.
 * Generated by PHPUnit on 2010-05-24 at 22:34:01.
 */
class DisplayTestOutput extends \PHPUnit_Extensions_OutputTestCase
{
    /**
     * @var Display
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Display;
    }

    public function testPrintHeader()
    {
        $this->expectOutputString(
'+---------------+---------------+---------------+
|      ID       |     Date      |     Value     |
+---------------+---------------+---------------+
'
);
        $this->object->printHeader();
    }

    public function testPrintFooter()
    {
        $this->expectOutputString("+---------------+---------------+---------------+\n");
        $this->object->printFooter();
    }

    public function testPrintRow()
    {
        $row = new \stdClass;
        $row->id = 1;
        $row->date = 1;
        $row->value = 1;

        $this->expectOutputString("| 1             | 1             | 1             |\n");
        $this->object->printRow($row);
    }


}
?>
